services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
    depends_on: []
    env_file:
      - .env
    restart: always
    networks: [default, postgres-net]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    restart: always
    networks: [default]

networks:
  default:
  postgres-net:
    external: true
